import { useState } from 'react';
import Head from 'next/head';
import { SearchBar } from '../components/SearchBar';
import { MovieCard } from '../components/MovieCard';
// Search OMDB API and return a list of movies that show at least the title, release year and a button to nominate them.
// Search results should only be of movies
//  Updates to the search terms should update the result list.
// If a movie has been nominated already, it's button should be disabled within in search results.
// Nominated movies should move to their own "Nomination List"
// Movies in the nomiation list should be able to be removed.
// Display a banner when the user has nominated 5 movies.

export default function Home() {
  const [searchQuery, setSearchQuery] = useState('');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Show search bar */}

      <main>
        <div className="bg-cyan-800 py-20">
          <h1 className="text-center text-6xl uppercase text-white font-bold">
            OMDB Movies
          </h1>

          <SearchBar
            onChange={(e) => setSearchQuery(e.target.value)}
            value={searchQuery}
          />
        </div>
        {searchQuery && (
          <>
            <div className="mx-auto w-8/12 mt-10">
              <h2 className="text-2xl">Results for "{searchQuery}"</h2>
            </div>
            <div className="mx-auto w-8/12 mt-10 flex gap-10 overflow-auto">
              <MovieCard name="Hell Yeah" />
              <MovieCard name="Hell Yeah" />
              <MovieCard name="Hell Yeah" />
              <MovieCard name="Hell Yeah" />
              <MovieCard name="Hell Yeah" />
              <MovieCard name="Hell Yeah" />
            </div>
          </>
        )}
      </main>

      <footer></footer>
    </div>
  );
}
