import Head from 'next/head';
// Search OMDB API and return a list of movies that show at least the title, release year and a button to nominate them.
// Search results should only be of movies
//  Updates to the search terms should update the result list.
// If a movie has been nominated already, it's button should be disabled within in search results.
// Nominated movies should move to their own "Nomination List"
// Movies in the nomiation list should be able to be removed.
// Display a banner when the user has nominated 5 movies.

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Show search bar */}

      <main>
        <div className="bg-cyan-800 py-20">
          <h1 className="text-center text-6xl uppercase text-white font-bold">
            OMDB Movies
          </h1>

          <div className="w-8/12 mx-auto border-2 rounded-full mt-20 flex items-center pl-8 bg-white shadow-lg">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-8 w-8 text-cyan-800"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
              />
            </svg>
            <input
              type="text"
              placeholder="Enter your favourite movie name..."
              className="rounded-full w-full px-6 py-8 focus:outline-none font-semibold text-2xl tracking-wider text-cyan-800"
            />
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
